### ISSUE TITLE
Faster loading of DamageClassification table

### ISSUE THREAD

**Issue by aronwc** [dssg/tweedr#2]

**Comment by aronwc** [comment]
Currently, the text of the tweet is loaded upon request by querying uniform_sample or keyword_sample tables.
Instead, we should use foreign keys and relationships to load this more efficiently

**Comment by chbrown** [comment]
See 2a1f9ba314dbc36b26a045165ceaf3f8487aac20 (`tweedr/models/__init__.py`) for an example of adding eager loading to a SQLAlchemy-mapped table.

Also see the SQLAlchemy docs on [Relationship Loading Techniques](http://docs.sqlalchemy.org/en/rel_0_8/orm/loading.html) for further config options (e.g., ways to specify such eager loads only on individual queries).
